update=5/21/2018 9:19:16 PM
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=transistors
LibName4=conn
LibName5=linear
LibName6=regul
LibName7=74xx
LibName8=cmos4000
LibName9=adc-dac
LibName10=memory
LibName11=xilinx
LibName12=microcontrollers
LibName13=dsp
LibName14=microchip
LibName15=analog_switches
LibName16=motorola
LibName17=texas
LibName18=intel
LibName19=audio
LibName20=interface
LibName21=digital-audio
LibName22=philips
LibName23=display
LibName24=cypress
LibName25=siliconi
LibName26=opto
LibName27=atmel
LibName28=contrib
LibName29=valves
LibName30=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Addressable-Specialty
LibName31=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Alarms-Buzzers-and-Sirens
LibName32=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Automotive-Relays
LibName33=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Balun
LibName34=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Barrel-Audio-Connectors
LibName35=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Battery-Holders-Clips-Contacts
LibName36=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Clock-Timing-Clock-Generators-PLLs-Frequency-Synthesizers
LibName37=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Clock-Timing-Programmable-Timers-and-Oscillators
LibName38=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Clock-Timing-Real-Time-Clocks
LibName39=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Coaxial-Connectors-RF
LibName40=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Current-Transducers
LibName41=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Data-Acquisition-ADCs-DACs-Special-Purpose
LibName42=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Data-Acquisition-Analog-to-Digital-Converters-ADC
LibName43=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Data-Acquisition-Digital-Potentiometers
LibName44=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Data-Acquisition-Digital-to-Analog-Converters-DAC
LibName45=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Data-Acquisition-Touch-Screen-Controllers
LibName46=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_DC-DC-Converters
LibName47=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Digital-Isolators
LibName48=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Diodes-Bridge-Rectifiers
LibName49=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Diodes-Rectifiers-Arrays
LibName50=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Diodes-Rectifiers-Single
LibName51=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Diodes-Zener-Single
LibName52=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Display-Modules-LED-Character-and-Numeric
LibName53=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_D-Sub-Connectors
LibName54=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Embedded-Microcontrollers
LibName55=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Encoders
LibName56=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Evaluation-Boards-Sensors
LibName57=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Ferrite-Beads-and-Chips
LibName58=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Fixed-Inductors
LibName59=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Fuses
LibName60=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Gas-Sensors
LibName61=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Humidity-Moisture-Sensors
LibName62=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Image-Sensors-Camera
LibName63=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Infrared-UV-Visible-Emitters
LibName64=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Inrush-Current-Limiters-ICL
LibName65=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Interface-Analog-Switches-Multiplexers-Demultiplexers
LibName66=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Interface-Analog-Switches-Special-Purpose
LibName67=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Interface-Controllers
LibName68=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Interface-Drivers-Receivers-Transceivers
LibName69=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Interface-I-O-Expanders
LibName70=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Interface-Modules
LibName71=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Interface-Sensor-and-Detector-Interfaces
LibName72=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Interface-Sensor-Capacitive-Touch
LibName73=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Interface-Specialized
LibName74=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_LED-Indication-Discrete
LibName75=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_LEDs-Circuit-Board-Indicators-Arrays-Light-Bars-Bar-Graphs
LibName76=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Linear-Amplifiers-Audio
LibName77=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Linear-Amplifiers-Instrumentation-OP-Amps-Buffer-Amps
LibName78=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Linear-Comparators
LibName79=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Logic-Buffers-Drivers-Receivers-Transceivers
LibName80=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Logic-Flip-Flops
LibName81=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Logic-Gates-and-Inverters
LibName82=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Logic-Multivibrators
LibName83=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Logic-Shift-Registers
LibName84=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Logic-Signal-Switches-Multiplexers-Decoders
LibName85=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Logic-Translators-Level-Shifters
LibName86=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Magnetic-Sensors-Compass-Magnetic-Field-Modules
LibName87=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Magnetic-Sensors-Linear-Compass-ICs
LibName88=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Magnetic-Sensors-Switches-Solid-State
LibName89=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Memory
LibName90=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Memory-Connectors-PC-Card-Sockets
LibName91=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Microphones
LibName92=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Modular-Connectors-Jacks
LibName93=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Modular-Connectors-Jacks-With-Magnetics
LibName94=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Motion-Sensors-Accelerometers
LibName95=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Motion-Sensors-IMUs-Inertial-Measurement-Units
LibName96=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Motion-Sensors-Tilt-Switches
LibName97=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Navigation-Switches-Joystick
LibName98=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Optical-Sensors-Ambient-Light-IR-UV-Sensors
LibName99=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Optical-Sensors-Photo-Detectors-Remote-Receiver
LibName100=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Optical-Sensors-Photodiodes
LibName101=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Optical-Sensors-Phototransistors
LibName102=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Optical-Sensors-Reflective-Analog-Output
LibName103=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Optoisolators-Logic-Output
LibName104=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Optoisolators-Transistor-Photovoltaic-Output
LibName105=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Optoisolators-Triac-SCR-Output
LibName106=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Oscillators
LibName107=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_PMIC-AC-DC-Converters-Offline-Switchers
LibName108=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_PMIC-Battery-Chargers
LibName109=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_PMIC-Battery-Management
LibName110=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_PMIC-Current-Regulation-Management
LibName111=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_PMIC-Full-Half-Bridge-Drivers
LibName112=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_PMIC-Gate-Drivers
LibName113=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_PMIC-LED-Drivers
LibName114=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_PMIC-Motor-Drivers-Controllers
LibName115=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_PMIC-OR-Controllers-Ideal-Diodes
LibName116=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_PMIC-Power-Distribution-Switches-Load-Drivers
LibName117=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_PMIC-Power-Management-Specialized
LibName118=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_PMIC-RMS-to-DC-Converters
LibName119=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_PMIC-Supervisors
LibName120=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_PMIC-Thermal-Management
LibName121=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_PMIC-V-F-and-F-V-Converters
LibName122=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_PMIC-Voltage-Reference
LibName123=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_PMIC-Voltage-Regulators-DC-DC-Switching-Controllers
LibName124=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_PMIC-Voltage-Regulators-DC-DC-Switching-Regulators
LibName125=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_PMIC-Voltage-Regulators-Linear
LibName126=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_PMIC-Voltage-Regulators-Special-Purpose
LibName127=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Power-Relays-Over-2-Amps
LibName128=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Pressure-Sensors-Transducers
LibName129=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Programmable-Oscillators
LibName130=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Pushbutton-Switches
LibName131=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Rectangular-Connectors-Headers-Male-Pins
LibName132=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Reed-Relays
LibName133=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Resistor-Networks-Arrays
LibName134=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_RF-Amplifiers
LibName135=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_RF-Antennas
LibName136=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_RF-Demodulators
LibName137=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_RF-Detectors
LibName138=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_RF-Evaluation-and-Development-Kits-Boards
LibName139=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_RFID-RF-Access-Monitoring-ICs
LibName140=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_RF-Receivers
LibName141=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_RF-Switches
LibName142=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_RF-Transceiver-ICs
LibName143=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_RF-Transceiver-Modules
LibName144=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_RF-Transmitters
LibName145=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Rotary-Potentiometers-Rheostats
LibName146=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Sensors-Transducers_Accessories
LibName147=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Signal-Relays-Up-to-2-Amps
LibName148=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Slide-Switches
LibName149=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Solid-State-Relays
LibName150=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Specialized-ICs
LibName151=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Specialized-Sensors
LibName152=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Surge-Suppression-ICs
LibName153=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Tactile-Switches
LibName154=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Temperature-Sensors-Analog-and-Digital-Output
LibName155=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Thermal-Cutoffs-Thermal-Fuses
LibName156=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Thyristors-DIACs-SIDACs
LibName157=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Thyristors-SCRs
LibName158=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Thyristors-TRIACs
LibName159=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Toggle-Switches
LibName160=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Transistors-Bipolar-BJT-Arrays
LibName161=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Transistors-Bipolar-BJT-RF
LibName162=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Transistors-Bipolar-BJT-Single
LibName163=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Transistors-Bipolar-BJT-Single-Pre-Biased
LibName164=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Transistors-FETs-MOSFETs-Arrays
LibName165=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Transistors-FETs-MOSFETs-RF
LibName166=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Transistors-FETs-MOSFETs-Single
LibName167=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Transistors-JFETs
LibName168=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Trimmer-Potentiometers
LibName169=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_TVS-Diodes
LibName170=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_TVS-Mixed-Technology
LibName171=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_USB-DVI-HDMI-Connectors
LibName172=libs/intersil-isl91127ir
