update=7/13/2018 12:17:09 PM
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[schematic_editor]
version=1
PageLayoutDescrFile=
PlotDirectoryName=
SubpartIdSeparator=0
SubpartFirstId=65
NetFmtName=Pcbnew
SpiceAjustPassiveValues=0
LabSize=60
ERC_TestSimilarLabels=1
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=SmartiePiNode-rescue
LibName2=power
LibName3=device
LibName4=transistors
LibName5=conn
LibName6=linear
LibName7=regul
LibName8=74xx
LibName9=cmos4000
LibName10=adc-dac
LibName11=memory
LibName12=xilinx
LibName13=microcontrollers
LibName14=dsp
LibName15=microchip
LibName16=analog_switches
LibName17=motorola
LibName18=texas
LibName19=intel
LibName20=audio
LibName21=interface
LibName22=digital-audio
LibName23=philips
LibName24=display
LibName25=cypress
LibName26=siliconi
LibName27=opto
LibName28=atmel
LibName29=contrib
LibName30=valves
LibName31=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Addressable-Specialty
LibName32=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Alarms-Buzzers-and-Sirens
LibName33=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Automotive-Relays
LibName34=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Balun
LibName35=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Barrel-Audio-Connectors
LibName36=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Battery-Holders-Clips-Contacts
LibName37=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Clock-Timing-Clock-Generators-PLLs-Frequency-Synthesizers
LibName38=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Clock-Timing-Programmable-Timers-and-Oscillators
LibName39=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Clock-Timing-Real-Time-Clocks
LibName40=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Coaxial-Connectors-RF
LibName41=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Current-Transducers
LibName42=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Data-Acquisition-ADCs-DACs-Special-Purpose
LibName43=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Data-Acquisition-Analog-to-Digital-Converters-ADC
LibName44=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Data-Acquisition-Digital-Potentiometers
LibName45=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Data-Acquisition-Digital-to-Analog-Converters-DAC
LibName46=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Data-Acquisition-Touch-Screen-Controllers
LibName47=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_DC-DC-Converters
LibName48=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Digital-Isolators
LibName49=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Diodes-Bridge-Rectifiers
LibName50=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Diodes-Rectifiers-Arrays
LibName51=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Diodes-Rectifiers-Single
LibName52=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Diodes-Zener-Single
LibName53=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Display-Modules-LED-Character-and-Numeric
LibName54=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_D-Sub-Connectors
LibName55=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Embedded-Microcontrollers
LibName56=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Encoders
LibName57=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Evaluation-Boards-Sensors
LibName58=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Ferrite-Beads-and-Chips
LibName59=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Fixed-Inductors
LibName60=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Fuses
LibName61=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Gas-Sensors
LibName62=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Humidity-Moisture-Sensors
LibName63=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Image-Sensors-Camera
LibName64=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Infrared-UV-Visible-Emitters
LibName65=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Inrush-Current-Limiters-ICL
LibName66=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Interface-Analog-Switches-Multiplexers-Demultiplexers
LibName67=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Interface-Analog-Switches-Special-Purpose
LibName68=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Interface-Controllers
LibName69=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Interface-Drivers-Receivers-Transceivers
LibName70=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Interface-I-O-Expanders
LibName71=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Interface-Modules
LibName72=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Interface-Sensor-and-Detector-Interfaces
LibName73=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Interface-Sensor-Capacitive-Touch
LibName74=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Interface-Specialized
LibName75=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_LED-Indication-Discrete
LibName76=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_LEDs-Circuit-Board-Indicators-Arrays-Light-Bars-Bar-Graphs
LibName77=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Linear-Amplifiers-Audio
LibName78=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Linear-Amplifiers-Instrumentation-OP-Amps-Buffer-Amps
LibName79=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Linear-Comparators
LibName80=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Logic-Buffers-Drivers-Receivers-Transceivers
LibName81=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Logic-Flip-Flops
LibName82=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Logic-Gates-and-Inverters
LibName83=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Logic-Multivibrators
LibName84=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Logic-Shift-Registers
LibName85=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Logic-Signal-Switches-Multiplexers-Decoders
LibName86=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Logic-Translators-Level-Shifters
LibName87=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Magnetic-Sensors-Compass-Magnetic-Field-Modules
LibName88=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Magnetic-Sensors-Linear-Compass-ICs
LibName89=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Magnetic-Sensors-Switches-Solid-State
LibName90=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Memory
LibName91=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Memory-Connectors-PC-Card-Sockets
LibName92=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Microphones
LibName93=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Modular-Connectors-Jacks
LibName94=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Modular-Connectors-Jacks-With-Magnetics
LibName95=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Motion-Sensors-Accelerometers
LibName96=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Motion-Sensors-IMUs-Inertial-Measurement-Units
LibName97=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Motion-Sensors-Tilt-Switches
LibName98=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Navigation-Switches-Joystick
LibName99=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Optical-Sensors-Ambient-Light-IR-UV-Sensors
LibName100=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Optical-Sensors-Photo-Detectors-Remote-Receiver
LibName101=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Optical-Sensors-Photodiodes
LibName102=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Optical-Sensors-Phototransistors
LibName103=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Optical-Sensors-Reflective-Analog-Output
LibName104=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Optoisolators-Logic-Output
LibName105=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Optoisolators-Transistor-Photovoltaic-Output
LibName106=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Optoisolators-Triac-SCR-Output
LibName107=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Oscillators
LibName108=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_PMIC-AC-DC-Converters-Offline-Switchers
LibName109=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_PMIC-Battery-Chargers
LibName110=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_PMIC-Battery-Management
LibName111=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_PMIC-Current-Regulation-Management
LibName112=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_PMIC-Full-Half-Bridge-Drivers
LibName113=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_PMIC-Gate-Drivers
LibName114=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_PMIC-LED-Drivers
LibName115=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_PMIC-Motor-Drivers-Controllers
LibName116=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_PMIC-OR-Controllers-Ideal-Diodes
LibName117=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_PMIC-Power-Distribution-Switches-Load-Drivers
LibName118=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_PMIC-Power-Management-Specialized
LibName119=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_PMIC-RMS-to-DC-Converters
LibName120=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_PMIC-Supervisors
LibName121=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_PMIC-Thermal-Management
LibName122=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_PMIC-V-F-and-F-V-Converters
LibName123=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_PMIC-Voltage-Reference
LibName124=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_PMIC-Voltage-Regulators-DC-DC-Switching-Controllers
LibName125=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_PMIC-Voltage-Regulators-DC-DC-Switching-Regulators
LibName126=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_PMIC-Voltage-Regulators-Linear
LibName127=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_PMIC-Voltage-Regulators-Special-Purpose
LibName128=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Power-Relays-Over-2-Amps
LibName129=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Pressure-Sensors-Transducers
LibName130=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Programmable-Oscillators
LibName131=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Pushbutton-Switches
LibName132=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Rectangular-Connectors-Headers-Male-Pins
LibName133=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Reed-Relays
LibName134=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Resistor-Networks-Arrays
LibName135=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_RF-Amplifiers
LibName136=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_RF-Antennas
LibName137=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_RF-Demodulators
LibName138=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_RF-Detectors
LibName139=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_RF-Evaluation-and-Development-Kits-Boards
LibName140=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_RFID-RF-Access-Monitoring-ICs
LibName141=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_RF-Receivers
LibName142=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_RF-Switches
LibName143=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_RF-Transceiver-ICs
LibName144=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_RF-Transceiver-Modules
LibName145=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_RF-Transmitters
LibName146=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Rotary-Potentiometers-Rheostats
LibName147=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Sensors-Transducers_Accessories
LibName148=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Signal-Relays-Up-to-2-Amps
LibName149=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Slide-Switches
LibName150=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Solid-State-Relays
LibName151=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Specialized-ICs
LibName152=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Specialized-Sensors
LibName153=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Surge-Suppression-ICs
LibName154=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Tactile-Switches
LibName155=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Temperature-Sensors-Analog-and-Digital-Output
LibName156=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Thermal-Cutoffs-Thermal-Fuses
LibName157=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Thyristors-DIACs-SIDACs
LibName158=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Thyristors-SCRs
LibName159=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Thyristors-TRIACs
LibName160=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Toggle-Switches
LibName161=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Transistors-Bipolar-BJT-Arrays
LibName162=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Transistors-Bipolar-BJT-RF
LibName163=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Transistors-Bipolar-BJT-Single
LibName164=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Transistors-Bipolar-BJT-Single-Pre-Biased
LibName165=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Transistors-FETs-MOSFETs-Arrays
LibName166=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Transistors-FETs-MOSFETs-RF
LibName167=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Transistors-FETs-MOSFETs-Single
LibName168=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Transistors-JFETs
LibName169=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_Trimmer-Potentiometers
LibName170=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_TVS-Diodes
LibName171=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_TVS-Mixed-Technology
LibName172=C:/Users/Stache/Documents/KiCad Projects/digikey-kicad-library/digikey-symbols/dk_USB-DVI-HDMI-Connectors
LibName173=libs/intersil-isl91127ir
LibName174=libs/st-stm32l052-lqfp48
LibName175=libs/usbmicrob
LibName176=libs/sw-push
LibName177=libs/micro-sd-card
LibName178=libs/crystal_small
LibName179=libs/abracon-abm10
LibName180=libs/m3-mounting-hole
LibName181=libs/spdt
